### ISSUE TITLE
File extensions need be validated with exact match

### ISSUE THREAD

**Issue by ddevassy** [VinnyBabuManjaly/copyright-action#2]
**Scenario**

In a NodeJS project, If user passes, .js as file extension in the workflow.

**Expected**
Copyright headers should be added only into js file.

**Current Behaviour**
Copyright headers are added in .js and .json files.

**Comment by ddevassy** [comment]
```
name: Insert Copyright to required files
on: [push]
jobs:
  build:
    name: Copyright
    runs-on: ubuntu-latest
    steps:
      # Checking out the repository which is to be actioned
      - uses: actions/checkout@v2
      # Implementing action on repository
      - name: Runs action to insert copyright
        uses: VinnyBabuManjaly/insert-copyright-action@v1.0.0
        with:
          CopyrightString: '// Copyright (c) 20 ABC Inc.\n// All rights reserved\n'
          FilePath: 'src'
          FileType: '.js'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
